# Generated by Django 3.2.9 on 2021-11-13 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 13, 11, 2, 8, 448821, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
